[package]
name = "unstruct"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.14.1"
config = "0.13.1"
clap = { version = "3.1.16", features = ["derive"] }

