[package]
name = "unstruct"
version = "0.1.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.15"
clap = { version = "3.2", features = ["derive"] }
glob = "0.3"
pest = "2.4"
pest_derive = "2.4"
